### ISSUE TITLE
NullPointerException on animation end

### ISSUE THREAD

**Issue by i-developer** [KeepSafe/TapTargetView#121]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:** 1.6.0

**Stack trace:**

Process: eu.trans.transexpress, PID: 1341
                                                                     java.lang.NullPointerException: Attempt to write to field 'android.view.ViewParent android.view.View.mParent' on a null object reference
                                                                         at android.view.ViewGroup.removeFromArray(ViewGroup.java:4420)
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4614)
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4578)
                                                                         at android.view.ViewGroup.removeView(ViewGroup.java:4509)
                                                                         at com.getkeepsafe.taptargetview.TapTargetView$7.onEnd(TapTargetView.java:317)
                                                                         at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$2.onAnimationEnd(FloatValueAnimatorBuilder.java:93)
                                                                         at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                         at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                         at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Android version:** 6

**Comment by xiphirx** [comment]
Seems to be the same as #49 . 

When are you dismissing the TapTargetView? What exact version of Android is used? What device is this from?  Can you share the code you're using to show the TapTargetView?

**Comment by i-developer** [comment]
Device: Samsung Note 4, Version: 6.0.1
Code:
Rect rect = new Rect(80, 110, 80, 140);
            TapTarget tapTarget =
                TapTarget.forBounds(rect, getString(R.string.te_OnboardingNewOptionsInMenuTitle),
                    getString(R.string.te_OnboardingNewOptionsInMenuText))
                    .outerCircleColor(
                        R.color.gray_background)      // Specify a color for the outer circle
                    .textColor(R.color.colorPrimary)            // Specify a color for text
                    .dimColor(
                        R.color.HeaderTopBorderColor)            // If set, will dim behind the view with 30% opacity of the given color
                    .drawShadow(false)                   // Whether to draw a drop shadow or not
                    .cancelable(
                        true)                  // Whether tapping outside the outer circle dismisses the view
                    .tintTarget(true)
                    .transparentTarget(true);
            ToolTipManager.showOnboarding(getActivity(), tapTarget,
                () -> mActivityController.showMenu(), MENU_ONBOARDING_ID);

**Comment by xiphirx** [comment]
I suspect that Samsung is doing something weird in `ViewGroup` as this bugreport https://code.google.com/p/android/issues/detail?id=77639 is the only other thing I can find on this type of crash and the 6.0.0 or 6.0.1 AOSP source for `ViewGroup` does not match the lines in the stack trace...

Is this crash something you can reproduce?

**Comment by i-developer** [comment]
I can't repeat this issue.

**Comment by xiphirx** [comment]
I'm going to just catch the exception then... It doesnt seem like there is much else I can do.
