### ISSUE TITLE
Error just by including dependency along with google services(version 11.0.1)

### ISSUE THREAD

**Issue by saurabhDuzumaki** [KeepSafe/TapTargetView#185]
- [x] I have verified the issue exists on the latest version - Yes
- [x] I am able to reproduce it - Yes, on many phones like Moto G 1st gen, Moto G5 Plus, OnePlus One, OnePlus 3T, Galaxy S7 Edge and emulators like Android Emulator, Nox Player etc. Both Rooted and un-rooted as well 

**Version used:**
1.9.1
**Stack trace:**
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.wonderstree.wonderstreecom/app.wonderstree.wonderstreecom.Main}: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class android.support.design.widget.NavigationView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                    Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class android.support.design.widget.NavigationView
                                                    Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.NavigationView
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at app.wonderstree.wonderstreecom.Main.onCreate(Main.java:76)
                                                       at android.app.Activity.performCreate(Activity.java:6684)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/view/menu/MenuBuilder;
                                                       at android.support.design.widget.NavigationView.<init>(NavigationView.java:95)
                                                       at android.support.design.widget.NavigationView.<init>(NavigationView.java:88)
                                                       at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at app.wonderstree.wonderstreecom.Main.onCreate(Main.java:76) 
                                                       at android.app.Activity.performCreate(Activity.java:6684) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6236) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
07-16 18:55:26.534 31501-31501/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.view.menu.MenuBuilder" on path: DexPathList[[zip file "/data/app/app.wonderstree.wonderstreecom-2/base.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_dependencies_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_0_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_1_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_2_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_3_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_4_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_5_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_6_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_7_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_8_apk.apk", zip file "/data/app/app.wonderstree.wonderstreecom-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/app.wonderstree.wonderstreecom-2/lib/arm, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       	... 27 more
**Android version:**
any

Explanation = I get above error with app force closing. I am getting this error even before writing any code related to tap targets. I am getting this error just by including your dependency in my app level build.gradle. When I remove your dependency, there are no more errors. Tap targets are working perfectly in a demo app which doesn't include Google services, on every device. Alternative like [this](https://github.com/sjwall/MaterialTapTargetPrompt) is working fine without any crash but has less features.

 It is also worth mentioning that previously I was getting error at this line 
 String refreshedToken = FirebaseInstanceId.getInstance().getToken();
        App.getInstance().setGcmToken(refreshedToken);
which somehow got resolved by updating dependency of the google services.
Restarted Android Studio 4-5 times, rebooted pc twice and rebooted devices too. Please help. Thanks you for your awesome work.

**Comment by xiphirx** [comment]
Are you using Proguard?

**Comment by saurabhDuzumaki** [comment]
No. I am not using Proguard.

**Comment by xiphirx** [comment]
What version of the support library are you using? I doubt this is an issue with TapTargetView.

**Comment by saurabhDuzumaki** [comment]
support library version is v4 25.3.1. I will be checking if issue is still there if I use dependency in my office build. This seems too fishy and it almost seems like there is some problem with my home setup because even inclusion is causing a problem.

**Comment by saurabhDuzumaki** [comment]
This is what I am getting on my office setup
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: app.wonderstree.wonderstreecom, PID: 5413
                                                                              java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/app.wonderstree.wonderstreecom-1/split_lib_dependencies_apk.apk:classes15.dex)
                                                                                  at com.google.firebase.iid.zzg.zzeC(Unknown Source)
                                                                                  at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                                  at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                                  at com.google.firebase.iid.zzd.zzb(Unknown Source)
                                                                                  at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                                  at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                                  at app.wonderstree.wonderstreecom.AppActivity.onCreate(AppActivity.java:45)
                                                                                  at android.app.Activity.performCreate(Activity.java:6684)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)`

While line 45 in AppActivity.java is
`String refreshedToken = FirebaseInstanceId.getInstance().getToken();
        App.getInstance().setGcmToken(refreshedToken);`

It was working fine without including dependency.

**Comment by xiphirx** [comment]
This seems like an issue with using an old version of play services / firebase with a support library >= 24, see https://stackoverflow.com/questions/40904466/java-lang-illegalaccesserror-method-void-android-support-v4-content

**Comment by saurabhDuzumaki** [comment]
Everything is working beautifully and gracefully after updating everything to the latest. Thank you very much for solving non-existent issue. This "issue" can be closed now.
