### ISSUE TITLE
java.lang.IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by cliffgr** [KeepSafe/TapTargetView#207]
- [+ ] I have verified the issue exists on the latest version
- [+] I am able to reproduce it

1.9.1

**FATAL EXCEPTION: main
                                                                  Process: wizzo.mbc.net.qa, PID: 13119
                                                                  java.lang.IndexOutOfBoundsException
                                                                      at android.view.ViewGroup.removeFromArray(ViewGroup.java:3811)
                                                                      at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3995)
                                                                      at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3959)
                                                                      at android.view.ViewGroup.removeView(ViewGroup.java:3891)
                                                                      at com.getkeepsafe.taptargetview.ViewUtil.removeView(ViewUtil.java:75)
                                                                      at com.getkeepsafe.taptargetview.TapTargetView$5.onEnd(TapTargetView.java:313)
                                                                      at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$2.onAnimationEnd(FloatValueAnimatorBuilder.java:91)
                                                                      at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
                                                                      at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
                                                                      at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
                                                                      at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:543)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5584)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                      at dalvik.system.NativeStart.main(Native Method)**

**4.4.4 Api 19 Samgung SM-G318H**

**Comment by Jawnnypoo** [comment]
@cliffgr If you know the reproduction steps, what are they exactly?
