### ISSUE TITLE
NPE on TapTargetView.dismiss()

### ISSUE THREAD

**Issue by falaksevak** [KeepSafe/TapTargetView#217]
- [YES] I have verified the issue exists on the latest version
- [NO] I am able to reproduce it

**Version used:**
1.9.1

**Stack trace:**
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from null array
       at com.getkeepsafe.taptargetview.TapTargetView.calculateDrawingBounds(SourceFile:964)
       at com.getkeepsafe.taptargetview.TapTargetView$1.onUpdate(SourceFile:245)
       at com.getkeepsafe.taptargetview.TapTargetView$6.onUpdate(SourceFile:319)
       at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$1.onAnimationUpdate(SourceFile:75)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1374)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:602)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:550)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1039)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1050)
       at com.getkeepsafe.taptargetview.TapTargetView.dismiss(SourceFile:815)
       at com.zoosk.zoosk.ui.fragments.ZFragment.dismissTapTargetView(SourceFile:679)
       at com.zoosk.zoosk.ui.fragments.ZFragment.onStop(SourceFile:573)
       at com.zoosk.zoosk.ui.fragments.v2.DiscoverFragment.onStop(SourceFile:223)
       at android.support.v4.app.Fragment.performStop(SourceFile:2384)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1363)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1528)
       at android.support.v4.app.BackStackRecord.executeOps(SourceFile:753)
       at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2363)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2149)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(SourceFile:2103)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:2013)
       at android.support.v4.app.FragmentManagerImpl$1.run(SourceFile:710)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Android version:**
Every

**More Info:**
I am using the non-cancellable TapTargetView and I show the View in onResume() and If the user background the app then I dismiss it in onStop().

Skeleton:
```
class ZFragment {
private TapTargetView mView;

void onResume() {
showTapTargetView();
}

void onStop() {
if(mView != null) {
mView.dismiss(false);
}
```

**Comment by xiphirx** [comment]
That stacktrace doesnt line up with 1.9.1, are you sure that is the version you're using?

**Comment by sunitvijay88** [comment]
Can we show custom layout when clicking on view ??

**Comment by xiphirx** [comment]
Closing due to lack of activity
