### ISSUE TITLE
NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by hannesa2** [KeepSafe/TapTargetView#260]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.11.0

**Stack trace:**

> Caused by java.lang.NullPointerException: Attempt to read from null array
>        at com.getkeepsafe.taptargetview.TapTargetView$1.onUpdate(TapTargetView.java:241)
>        at com.getkeepsafe.taptargetview.TapTargetView$6.onUpdate(TapTargetView.java:308)
>        at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$1.onAnimationUpdate(FloatValueAnimatorBuilder.java:75)
>        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
>        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:612)
>        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:578)
>        at android.animation.ValueAnimator.start(ValueAnimator.java:1001)
>        at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
>        at com.getkeepsafe.taptargetview.TapTargetView.dismiss(TapTargetView.java:746)
>        at de.company.app.ui.coupons.list.CouponsFragment.onPause(CouponsFragment.java:557)
>        at android.support.v4.app.Fragment.performPause(Fragment.java:2449)
>        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1476)
>        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
>        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
>        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
>        at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3195)
>        at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:225)
>        at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:420)
>        at de.company.core.ui.BaseActivityCore.onPause(BaseActivityCore.java:152)
>        at android.app.Activity.performPause(Activity.java:7133)

**Android version:** 7.0

I see this very often in our app.
Thank you !

**Comment by xiphirx** [comment]
cf27a77c0d1b80601eeeaa8aed7167d718742863

**Comment by hannesa2** [comment]
When we will see a new version with this fix ?
I eager to see it. Thank you !

**Comment by xiphirx** [comment]
Unsure at the moment. If you need the fix now you can always use a snapshot: https://jitpack.io/#KeepSafe/TapTargetView/-SNAPSHOT

**Comment by wappier** [comment]
I have tha problem too

`java.lang.NullPointerException: Attempt to read from null array
	at com.getkeepsafe.taptargetview.TapTargetView$8.onUpdate(TapTargetView.java:329)
	at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$1.onAnimationUpdate(FloatValueAnimatorBuilder.java:75)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)
	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1316)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1446)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by cliffgr** [comment]
@xiphirx  why we have to use Snapshot what is the diference with release 1.10.0 and 1.11.0 ?
Whats is the Revision of Snapshot ?
