### ISSUE TITLE
Usage with a RecyclerView

### ISSUE THREAD

**Issue by vetrx** [KeepSafe/TapTargetView#267]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:1.11.0**

Firstly, congrats and thanks for making this useful library.
I wanted to let you know of a few issues that we encountered while using it with a `RecyclerView`, explained as follows:

Background to this issue is that we have a `RecyclerView` in one of the screens with each item displaying an `ImageView`. 
We create a `TapTarget` for one of these item's `ImageView` and draw the `TapTargeView`.
We use the standard `showFor(Activity activity, ... )` static method for the same.

While doing that, we have been facing few intermittent issues where, in spite of invoking `showFor()` with the correct View, `TapTargetView` does not get drawn on the screen. Specifically:
- The creation routines tend to get called, but the `TapTargetView` is not visible. One would assume that it was created and dismissed, but thats not the case. It's still present on the screen, that's why..
- The `TapTargetView` eats all the touch events. Confirmed that `TapTargetView#onTouchEvent(MotionEvent e)` gets called. This gives the impression that the app screen is unresponsive.
- As work around, I tried adding a touch listener on the `TapTargetView` and dismissing the `TapTargetView` from the listener. However, that gives a crash. Stack trace below.

`                                                                            java.lang.NullPointerException: Attempt to read from null array
                                                                                at com.getkeepsafe.taptargetview.TapTargetView$1.onUpdate(TapTargetView.java:241)
                                                                                at com.getkeepsafe.taptargetview.TapTargetView$6.onUpdate(TapTargetView.java:308)
                                                                                at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$1.onAnimationUpdate(FloatValueAnimatorBuilder.java:75)
                                                                                at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)
                                                                                at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:654)
                                                                                at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:617)
                                                                                at android.animation.ValueAnimator.start(ValueAnimator.java:1046)
                                                                                at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
                                                                                at com.getkeepsafe.taptargetview.TapTargetView.dismiss(TapTargetView.java:746)`

**Comment by xiphirx** [comment]
Can you try again with debug drawing enabled? `.setDrawDebug(true)`

Also make sure youre targeting a view that is currently shown on screen.

**Comment by vetrx** [comment]
I did try again with debug drawing enabled and in the above scenario I can see that the debug drawer does not get rendered either.

If it helps, I did find a workaround. We can add a touch listener to `TapTargetView` and not do `#dismiss()`, rather we can traverse the parent view and do a `removeView()` for the `TapTargetView`. This sacrifices the dismiss animation, but at least prevents the crash.

**Comment by xiphirx** [comment]
If you don't see the debug drawing happening that means you're targeting a view that isn't on screen / isn't laid out. The issue here is `outerCircleCenter` which can only be determined when the view is laid out on screen, is null. So nothing is drawn because its null and it crashes because you're dismissing before it even gets a chance to show, which you can see by checking `isVisible`.

**Comment by CalvinKern** [comment]
@vetrx I was able to use this library in a RecyclerView with no problems. I did all the necessary work in the adapter's `onViewAttachedToWindow()` method, this ensured that the view was already visible and that the library would work as intended.
