### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be &gt; 0

### ISSUE THREAD

**Issue by nitintechjini** [KeepSafe/TapTargetView#283]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**1.11.0

**Stack trace:** java.lang.IllegalArgumentException: width and height must be &gt; 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:882)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:849)
	at com.getkeepsafe.taptargetview.ViewTapTarget$1.void run()(Unknown Source)
	at com.getkeepsafe.taptargetview.ViewUtil$1.void onGlobalLayout()(Unknown Source)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2124)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Android version:**
7.1.1

Please look into this issue.

**Comment by xiphirx** [comment]
This means your View is 0x0 in size.
