### ISSUE TITLE
Twice call same hint - exception 

### ISSUE THREAD

**Issue by pavel-korolenkov** [KeepSafe/TapTargetView#30]
Hello! I try use your library.
What I doing - call my method, then press target, then call method - app falls.

My method:
TapTargetView.showFor(this,
                TapTarget.forView(target, "My target", "My description")
                        .tintTarget(false) // Whether to tint the target view's color
                        .drawShadow(true) // Whether to draw the drop shadow
                        .cancelable(false),
                new TapTargetView.Listener() {
                    @Override
                    public void onTargetClick(TapTargetView view) {
                        super.onTargetClick(view);
                        Toast.makeText(getApplicationContext(), "onTargetClick", Toast.LENGTH_SHORT).show();
                    }
                }
        );
where target - FloatingActionButton

                  java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3b22c126
                      at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
                      at android.graphics.Canvas.drawBitmap(Canvas.java:1416)
                      at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:538)
                      at com.getkeepsafe.taptargetview.TapTargetView.onDraw(TapTargetView.java:483)
                      at android.view.View.draw(View.java:15231)
                      at android.view.View.buildDrawingCacheImpl(View.java:14477)
                      at android.view.View.buildDrawingCache(View.java:14339)
                      at android.view.View.updateDisplayListIfDirty(View.java:14148)
                      at android.view.View.getDisplayList(View.java:14189)
                      at android.view.View.draw(View.java:14959)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                      at android.view.View.draw(View.java:15234)
                      at android.widget.FrameLayout.draw(FrameLayout.java:598)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
                      at android.view.View.updateDisplayListIfDirty(View.java:14167)
                      at android.view.View.getDisplayList(View.java:14189)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                      at android.view.Choreographer.doFrame(Choreographer.java:550)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by xiphirx** [comment]
Yup, I found this issue today while working on a different issue. I'm investigating a proper fix for it.

**Comment by xiphirx** [comment]
Actually, are you saying that you're re-using the same `TapTarget` instance twice? If so, that would make sense... You should only be using one target per `TapTargetView`
