### ISSUE TITLE
Support action bar seems to be not supported?

### ISSUE THREAD

**Issue by Syjgin** [KeepSafe/TapTargetView#303]
- [*] I have verified the issue exists on the latest version
- [*] I am able to reproduce it

**Version used:**
1.11.0
**Stack trace:**
```
java.lang.IllegalArgumentException: Given null view to target
        at com.getkeepsafe.taptargetview.ViewTapTarget.<init>(ViewTapTarget.java:31)
        at com.getkeepsafe.taptargetview.ToolbarTapTarget.<init>(ToolbarTapTarget.java:36)
        at com.getkeepsafe.taptargetview.TapTarget.forToolbarMenuItem(TapTarget.java:153)
        at com.getkeepsafe.taptargetview.TapTarget.forToolbarMenuItem(TapTarget.java:147)
        at me.talkout.androidapp.ui.fragment.supporttopiclist.SupportTopicListFragment.showTutorial(SupportTopicListFragment.kt:105)
        at me.talkout.androidapp.ui.fragment.supporttopiclist.SupportTopicListFragment.onCreateOptionsMenu(SupportTopicListFragment.kt:60)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2450)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3296)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:322)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:365)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
**Android version:**
8.1.0

Hello.
I'm trying to use TapTargetView with support action bar. I have activity with drawer layout & fragments with their own option menus.
Main activity layout:
```
<?xml version="1.0" encoding="utf-8"?>
 <android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/drawerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        tools:context=".ui.activity.main.MainActivity"
        android:background="@drawable/main_background">
        <FrameLayout
            android:id="@+id/contentFrame"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <!--suppress AndroidDomInspection -->
            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:theme="@style/ThemeActionBar"
                app:titleTextColor="@color/white"
                android:translationZ="1dp"
                />
        </FrameLayout>

        <android.support.design.widget.NavigationView
            android:id="@+id/navView"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:fitsSystemWindows="true"
            background="@color/menu_color"
            app:menu="@menu/burger_pupil"
            app:headerLayout="@layout/menu_header"
            />
    </android.support.v4.widget.DrawerLayout>
```
Fragment menu is loaded as follows:
```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setHasOptionsMenu(true)
    }
override fun onCreateOptionsMenu(menu: Menu?, inflater: MenuInflater?) {
        super.onCreateOptionsMenu(menu, inflater)
        inflater?.inflate(R.menu.chat_list_menu, menu)
        this.menu = menu
    }
```
Trying to show TapTargetView:
```
        //activity?.toolbar?.inflateMenu(R.menu.chat_list_menu) //<- this isn`t helps
        //onPrepareOptionsMenu(activity?.toolbar?.menu) //this too
        TapTargetView.showFor(activity,
                TapTarget.forToolbarMenuItem(activity!!.toolbar, R.id.newTopic, getString(R.string.add_support_topic))
                        .outerCircleColor(R.color.bright_blue)
                        .outerCircleAlpha(0.66f)
                ,
                object : TapTargetView.Listener() {
                    override fun onTargetClick(view: TapTargetView?) {
                        super.onTargetClick(view)
                        presenter.tutorialFinished()
                    }
                })
```
Maybe there are some example of usage TapTargetView with SupportActionBar?

**Comment by Syjgin** [comment]
Ok, it's solved by adding time interval after fragment creation - fragment menu must be already created before show

**Comment by iamkjn** [comment]
final Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                TapTargetView.showFor(activity,
                        TapTarget.forToolbarMenuItem(((Home_Activity) activity).toolbar, R.id.action_target
                                , "Test").outerCircleColor(R.color.colorAccent)
                                .outerCircleAlpha(0.66f));


            }
        }, 200);
