### ISSUE TITLE
Tap Targets for BottomNavigationView

### ISSUE THREAD

**Issue by rakave** [KeepSafe/TapTargetView#325]
- [ Y] I have verified the issue exists on the latest version
- [ Y] I am able to reproduce it

Android BottomNavigationView does not provide getActionView. So how would I go about implementing Tap Targets for a Bottom Navigation View? Any thoughts? I have tries getactionview, typecasting the ids, etc.

**Stack trace:**
java.lang.IllegalArgumentException: Given null view to target
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3493)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3533)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2791)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6342)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.IllegalArgumentException: Given null view to target
        at com.getkeepsafe.taptargetview.ViewTapTarget.<init>(ViewTapTarget.java:31)
        at com.getkeepsafe.taptargetview.TapTarget.forView(TapTarget.java:175)
        at com.getkeepsafe.taptargetview.TapTarget.forView(TapTarget.java:170)
        at com.twenty.four.crafts.CraftsmenDashboard.initializettv(CraftsmenDashboard.java:175)
        at com.twenty.four.crafts.CraftsmenDashboard.onResume(CraftsmenDashboard.java:295)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
        at android.app.Activity.performResume(Activity.java:6984)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3470)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3533) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2791) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6342) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 

**Android version:**
API : 26

**Comment by MoustafaElsaghier** [comment]
any idea how to do it, please?

can you provide us an example?
