### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID

### ISSUE THREAD

**Issue by myaghobi** [KeepSafe/TapTargetView#357]
- [X] I have verified the issue exists on the latest version

**Version used:** 1.12.0

**Android version:** 6.0

**Stack trace:**
`Failure getting entry for 0xffeff2ed (t=238 e=62189) (error -2147483647)
07-24 14:24:40.405 com.mypackage W: android.content.res.Resources$NotFoundException: Resource ID #0xffeff2ed
        at android.content.res.Resources.getValue(Resources.java:1384)
        at android.content.res.Resources.getColor(Resources.java:996)
        at android.content.Context.getColor(Context.java:441)
        at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:409)
        at com.getkeepsafe.taptargetview.TapTarget.colorResOrInt(TapTarget.java:489)
        at com.getkeepsafe.taptargetview.TapTarget.titleTextColorInt(TapTarget.java:470)
        at com.getkeepsafe.taptargetview.TapTargetView.applyTargetOptions(TapTargetView.java:608)
        at com.getkeepsafe.taptargetview.TapTargetView.<init>(TapTargetView.java:427)
        at com.getkeepsafe.taptargetview.TapTargetView.showFor(TapTargetView.java:166)
        at com.getkeepsafe.taptargetview.TapTargetSequence.showNext(TapTargetSequence.java:193)
07-24 14:24:40.406 com.mypackage W:     at com.getkeepsafe.taptargetview.TapTargetSequence.start(TapTargetSequence.java:126)
        at com.mypackage.MainActivity.onCreate(MainActivity.java:252)
        at android.app.Activity.performCreate(Activity.java:6367)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
        at android.app.ActivityThread.access$900(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

My Code:
```
TapTargetSequence sequence = new TapTargetSequence((Activity)context)
            .targets(
                    TapTarget.forView(findViewById(R.id.toggle_view),"title", "desc")
                            .titleTextSize(18)
                            .titleTextColor(lColors.getColorContentLight())
                            .descriptionTextSize(14)
                            .descriptionTextColor(lColors.getColorContentLight())
                            .textColor(lColors.getColorContentLight()),
                    TapTarget.forView(findViewById(R.id.toggle_view),"title", "desc")
                            .titleTextSize(18)
                            .titleTextColor(lColors.getColorContentLight())
                            .descriptionTextSize(14)
                            .descriptionTextColor(lColors.getColorContentLight())
                            .textColor(lColors.getColorContentLight())
            )
            .listener(new TapTargetSequence.Listener() {
                // This listener will tell us when interesting(tm) events happen in regards
                // to the sequence
                @Override
                public void onSequenceFinish() {
                    System.out.println("--------------- onSequenceFinish");
                    // Yay
                }

                @Override
                public void onSequenceStep(TapTarget lastTarget, boolean targetClicked) {
                    System.out.println("--------------- onSequenceStep lastTarget:" + lastTarget + " targetClicked:" + targetClicked);
                }

                @Override
                public void onSequenceCanceled(TapTarget lastTarget) {
                    System.out.println("--------------- onSequenceCanceled");
                }
            });
            sequence.start();
```

**Comment by myaghobi** [comment]
I fixed it by changing colors to resource id and taptargetview is working fine.
