### ISSUE TITLE
Error with FAB (I guess AppCompat)

### ISSUE THREAD

**Issue by Guilherme-HRamos** [KeepSafe/TapTargetView#43]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.3.0
**Stack trace:**
`No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager);`
**Android version:**
6.0

After add to gradle, and try to recompile apk, when I run, shows me that error.
here is my gradle configurations:

compileSdkVersion 23
buildToolsVersion '24.0.1'
minSdkVersion 17
targetSdkVersion 22
classpath 'com.android.tools.build:gradle:2.2.1'

**Comment by Guilherme-HRamos** [comment]
Here is all stack:

```
FATAL EXCEPTION: main
                                                                   Process: ft.projetorisadinha, PID: 8320
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{ft.projetorisadinha/ft.projetorisadinha.activities.ActivityPrincipal}: android.view.InflateException: Binary XML file line #87: Binary XML file line #87: Error inflating class android.support.design.widget.FloatingActionButton
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                    Caused by: android.view.InflateException: Binary XML file line #87: Binary XML file line #87: Error inflating class android.support.design.widget.FloatingActionButton
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                       at ft.projetorisadinha.activities.ActivityPrincipal.onCreate(ActivityPrincipal.java:132)
                                                                       at android.app.Activity.performCreate(Activity.java:6582)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                       at android.os.Looper.loop(Looper.java:207) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                    Caused by: android.view.InflateException: Binary XML file line #87: Error inflating class android.support.design.widget.FloatingActionButton
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at ft.projetorisadinha.activities.ActivityPrincipal.onCreate(ActivityPrincipal.java:132) 
                                                                       at android.app.Activity.performCreate(Activity.java:6582) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                       at android.os.Looper.loop(Looper.java:207) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at ft.projetorisadinha.activities.ActivityPrincipal.onCreate(ActivityPrincipal.java:132) 
                                                                       at android.app.Activity.performCreate(Activity.java:6582) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                       at android.os.Looper.loop(Looper.java:207) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                    Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager;)V in class Landroid/support/v7/widget/AppCompatImageHelper; or its super classes (declaration of 'android.support.v7.widget.AppCompatImageHelper' appears in /data/data/ft.projetorisadinha/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.2.1_0cf966e5977fccd8ee292dc592d43a054bbfd5d9-classes.dex)
                                                                       at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:133)
                                                                       at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:110)
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at ft.projetorisadinha.activities.ActivityPrincipal.onCreate(ActivityPrincipal.java:132) 
                                                                       at android.app.Activity.performCreate(Activity.java:6582) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                       at android.os.Looper.loop(Looper.java:207) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 

```

**Comment by Guilherme-HRamos** [comment]
solved changing version gradle of my app v7 library to 24.2
