### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by mgursch** [KeepSafe/TapTargetView#55]
Hello

im facing an NPE in fabrics crash dashboard, but dont know how to solve this. can you give me a hint please?

i have a sequence of two items. first is a toolbar action item second is a spinner view. it works correctly on my phone but crashes a lot on my users phones.

Fatal Exception: java.lang.NullPointerException: Attempt to read from null array
       at com.getkeepsafe.taptargetview.TapTargetView$10.onClick(TapTargetView.java:435)
       at android.view.View.performClick(View.java:5207)
       at android.view.View$PerformClick.run(View.java:21168)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by xiphirx** [comment]
Hi, can you share the code that creates the sequence, and the code that launches the sequence?

**Comment by mgursch** [comment]
because of the fix there is no need of source code?
when will v1.5.1 be released?

thanks a lot for your support

**Comment by xiphirx** [comment]
There is currently no date for 1.5.1 there is one other issue I want to resolve before it's released. In the mean time you can use a snapshot, which will be just as stable as a release
