### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by mgursch** [KeepSafe/TapTargetView#62]
- [x] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**
1.5.1

**Stack trace:**
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isLaidOut()' on a null object reference
       at com.getkeepsafe.taptargetview.ViewUtil.isLaidOut(ViewUtil.java:28)
       at com.getkeepsafe.taptargetview.ViewUtil.onLaidOut(ViewUtil.java:36)
       at com.getkeepsafe.taptargetview.ViewTapTarget.onReady(ViewTapTarget.java:35)
       at com.getkeepsafe.taptargetview.TapTargetView$9.run(TapTargetView.java:400)
       at com.getkeepsafe.taptargetview.ViewUtil$1.onGlobalLayout(ViewUtil.java:60)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:889)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2070)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
**Android version:**
Fabric shows this crash for Android 4.x, 5.x and 6.x

Greets

**Comment by xiphirx** [comment]
It seems like you're passing in a null view reference to `ViewTapTarget`. The library should fail sooner, so I'll make a change for that. Otherwise this doesn't seem to be an issue with the library

**Comment by mgursch** [comment]
Hey this is my code. I have NP check before adding a TapTarget. What should I add to prevent this NPE?

List<TapTarget> targets = new ArrayList<>();

                if (toolbar != null && !searchShowed) {
                    TapTarget targetToolbarSearch = TapTarget.forToolbarMenuItem(toolbar,
                            menuSearchID,
                            activity.getString(R.string.showcase_search_title),
                            activity.getString(R.string.showcase_search_text))
                                                             .dimColor(android.R.color.background_dark)
                                                             .tintTarget(true)
                                                             .id(TARGET_ID_SEARCH)
                                                             .drawShadow(true);

                    targets.add(targetToolbarSearch);
                }

                if (spinner != null) {
                    TapTarget targetSpinner = TapTarget.forView(spinner,
                            activity.getString(R.string.showcase_sort_title),
                            activity.getString(R.string.showcase_sort_text))
                                                       .dimColor(android.R.color.background_dark)
                                                       .tintTarget(true)
                                                       .id(TARGET_ID_SORT)
                                                       .drawShadow(true);

                    targets.add(targetSpinner);
                }

**Comment by xiphirx** [comment]
Are you making sure you inflate your `Toolbar`'s menu before you try to show the target for `menuSearchID` ?

**Comment by mgursch** [comment]
Whole code is running with 300ms delay. Toolbar menu items should be inflated, but maybe this is the problem.

can you please check that the library not forces a crash if it runs into that state?

Its better to not show the target than to crash ;)

**Comment by xiphirx** [comment]
Relying on a fixed time delay is not going to work, inflation time varies from device to device. You should only show the tap target if the `Toolbar` finished inflating its menu.

Crashing here is the correct thing to do. You should not be passing in a null view.
