### ISSUE TITLE
Android below API 21: TapTargetView

### ISSUE THREAD

**Issue by vados60** [KeepSafe/TapTargetView#74]
+ [ ] I have verified the issue exists on the latest version
+ [ ] I am able to reproduce it

**Version used:**
        compile 'com.getkeepsafe.taptargetview:taptargetview:1.5.2'
**Stack trace:**
FATAL EXCEPTION: main
                                                                java.lang.IllegalArgumentException: Layout: -240 < 0
                                                                    at android.text.Layout.<init>(Layout.java:138)
                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:104)
                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:90)
                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:68)
                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:48)
                                                                    at com.getkeepsafe.taptargetview.TapTargetView.updateTextLayouts(TapTargetView.java:714)
                                                                    at com.getkeepsafe.taptargetview.TapTargetView$9.run(TapTargetView.java:399)
                                                                    at com.getkeepsafe.taptargetview.ViewUtil$1.onGlobalLayout(ViewUtil.java:60)
                                                                    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:808)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1768)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:532)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                    at android.os.Handler.handleCallback(Handler.java:730)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:525)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Android version:**
API < 21

**Comment by julioz** [comment]
Just got the same crash on API 25, when trying to set a TapTargetView on a TextView that is in a ViewHolder of a recycler view row.

Here is the stack trace:

```
java.lang.IllegalArgumentException: Layout: -280 < 0                                                                                
   at android.text.Layout.<init>(Layout.java:182)                                                                                
   at android.text.StaticLayout.<init>(StaticLayout.java:478)                                                                                
   at android.text.StaticLayout.<init>(StaticLayout.java:464)                                                                                
   at android.text.StaticLayout.<init>(StaticLayout.java:442)                                                                                
   at android.text.StaticLayout.<init>(StaticLayout.java:422)                                                                                
   at com.getkeepsafe.taptargetview.TapTargetView.updateTextLayouts(TapTargetView.java:714)                                                                                
   at com.getkeepsafe.taptargetview.TapTargetView$9.run(TapTargetView.java:399)                                                                                
   at com.getkeepsafe.taptargetview.ViewUtil$1.onGlobalLayout(ViewUtil.java:60)                                                                                
   at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)                                                                                
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2106)                                                                                
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)                                                                                
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)                                                                                
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)                                                                                
   at android.view.Choreographer.doCallbacks(Choreographer.java:686)                                                                                
   at android.view.Choreographer.doFrame(Choreographer.java:621)                                                                                
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)                                                                                
   at android.os.Handler.handleCallback(Handler.java:751)                                                                                
   at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                
   at android.os.Looper.loop(Looper.java:154)                                                                                
   at android.app.ActivityThread.main(ActivityThread.java:6119)                                                                                
   at java.lang.reflect.Method.invoke(Native Method)                                                                                
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)                                                                                
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by xiphirx** [comment]
It seems like this issue is caused by `TapTargetView` not having enough room to display the text given. I have added a fix that will prevent this crash, however it seems like not having enough room would lead to something along the lines of #80
