### ISSUE TITLE
IndexOutOfBoundsException while dismissing

### ISSUE THREAD

**Issue by jkwiecien** [KeepSafe/TapTargetView#78]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.5.1

**Stack trace:**
```
                  java.lang.IndexOutOfBoundsException
                      at android.view.ViewGroup.removeFromArray(ViewGroup.java:4774)
                      at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4959)
                      at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4923)
                      at android.view.ViewGroup.removeView(ViewGroup.java:4854)
                      at com.getkeepsafe.taptargetview.TapTargetView$7.onEnd(TapTargetView.java:312)
                      at com.getkeepsafe.taptargetview.FloatValueAnimatorBuilder$2.onAnimationEnd(FloatValueAnimatorBuilder.java:93)
                      at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                      at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                      at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                      at android.view.Choreographer.doFrame(Choreographer.java:628)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7224)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Android version:**
6.0

Happens when dismissing tutorial.
```
                    TapTargetView tutorialView = TapTargetView.showFor(getActivity(),
                            Tutorials.buildTapTarget(),
                            new TapTargetView.Listener() {
                                @Override
                                public void onTargetClick(TapTargetView view) {
                                    view.dismiss(true);
                                    startSomeActivity()
                                }
                            });

    public static TapTarget buildTapTarget() {
        Context context = target.getContext();
        return TapTarget.forView(target, "title", "description")
                .id(1)
                .outerCircleColor(R.color.tutorial_bg_color)
                .targetCircleColor(R.color.white)
                .titleTextSize(20)
                .descriptionTextSize(15)
                .textColor(R.color.white)
                .dimColor(R.color.black)
                .cancelable(true)
                .transparentTarget(true);
    }
```

**Comment by xiphirx** [comment]
Thanks for the report. I'll look into it...

**Comment by xiphirx** [comment]
Actually, I believe this may be related to #59, can you please update to the latest release and try to reproduce it again?

**Comment by xiphirx** [comment]
Closing due to lack of activity. Comment if you still need help or have new info to add
