### ISSUE TITLE
IllegalArgumentException before laying out ViewTapTarget on Marshmallow

### ISSUE THREAD

**Issue by julioz** [KeepSafe/TapTargetView#89]
- [X] I have verified the issue exists on the latest version
- [X] I am able to reproduce it

**Version used:**
1.6.0

**Stack trace:**
```
Process: com.soundcloud.android.debug, PID: 2383 
java.lang.IllegalArgumentException: width and height must be > 0                                                                              
   at android.graphics.Bitmap.createBitmap(Bitmap.java:855)                                                                              
   at android.graphics.Bitmap.createBitmap(Bitmap.java:834)                                                                              
   at android.graphics.Bitmap.createBitmap(Bitmap.java:801)                                                                              
   at com.getkeepsafe.taptargetview.ViewTapTarget$1.run(ViewTapTarget.java:47)                                                                              
   at com.getkeepsafe.taptargetview.ViewUtil$1.onGlobalLayout(ViewUtil.java:60)                                                                              
   at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)                                                                              
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1981)                                                                              
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)                                                                              
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)                                                                              
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)                                                                              
   at android.view.Choreographer.doCallbacks(Choreographer.java:670)                                                                              
   at android.view.Choreographer.doFrame(Choreographer.java:606)                                                                              
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)                                                                              
   at android.os.Handler.handleCallback(Handler.java:746)                                                                              
   at android.os.Handler.dispatchMessage(Handler.java:95)                                                                              
   at android.os.Looper.loop(Looper.java:148)                                                                              
   at android.app.ActivityThread.main(ActivityThread.java:5443)                                                                              
   at java.lang.reflect.Method.invoke(Native Method)                                                                              
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)                                                                              
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Android version:**
6.0 Marshmallow

**Comment by xiphirx** [comment]
Hi, thanks for the report. I noticed you opened a PR to fix this issue, which is appreciated. 

From the stacktrace, I'm more concerned about the possibility of trying to target a view that, indeed, has a 0x0 size. Are you sure your target view is visible? Is the view being manually sized in code? 

You mention that you are reproducing this on Marshmallow, which is making me thing the change in your PR is hiding the issue. That is, unless `View.isLaidOut()` is broken.

**Comment by julioz** [comment]
@xiphirx Thanks for the quick answer.

In fact the view I'm targeting is inflated in code - but it is actually animating to its final position.
I found interesting that `View.isLaidOut()` actually backports to checking `width` and `height` in pre-KitKat, but it has a different implementation afterwards, checking some internal private flags:
```
public boolean isLaidOut() {
  return (mPrivateFlags3 & PFLAG3_IS_LAID_OUT) == PFLAG3_IS_LAID_OUT;
}
```

Not sure how these flags work though (specially related to transient states as animations) - but I was guessing there was no problem to add the check to the return statement as it is what happens in previous android versions. What do you think?

**Comment by xiphirx** [comment]
The updated check to use `ViewCompat` is fine and should be done, I'm just concerned that we're not throwing an exception when you're trying to show a tap target on an invisible or 0x0 view.

If the view you're targeting is animating to a final position, are you calling `show` at the start or end of the animation?

**Comment by julioz** [comment]
I'm guessing it is the result of a race condition. The View I'm targeting is held by an `AppBarLayout` and the animation I refer to is the `expand/collapse` animation that happens between states. Interestingly enough, this is the code for the `setExpanded` method in AOSP:
```
public void setExpanded(boolean expanded) {
    setExpanded(expanded, ViewCompat.isLaidOut(this));
}
```
While the following call goes to:
```
public void setExpanded(boolean expanded, boolean animate) {
    mPendingAction = (expanded ? PENDING_ACTION_EXPANDED : PENDING_ACTION_COLLAPSED)
                | (animate ? PENDING_ACTION_ANIMATE_ENABLED : 0);
    requestLayout();
}
```

Unfortunately there is this `mPendingAction` flag that will result in a state change as a consequence of the `requestLayout` call.
As you can see, it is not a simple case as I cannot really control the animation nor the view rendering in that `AppBarLayout` unfortunately.

**Comment by xiphirx** [comment]
I see... Not sure what to do about this at the moment. It seems like an edge case I would need to get more user reports about for it to be worth caring about. I'll close this issue in the meantime.
