### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ahmadnajar10** [KeepSafe/TapTargetView#99]
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**1.5.0**

**FATAL EXCEPTION: main
                                                                   java.lang.IllegalArgumentException: Layout: -160 < 0
                                                                       at android.text.Layout.<init>(Layout.java:138)
                                                                       at android.text.StaticLayout.<init>(StaticLayout.java:104)
                                                                       at android.text.StaticLayout.<init>(StaticLayout.java:90)
                                                                       at android.text.StaticLayout.<init>(StaticLayout.java:68)
                                                                       at android.text.StaticLayout.<init>(StaticLayout.java:48)
                                                                       at com.getkeepsafe.taptargetview.TapTargetView.updateTextLayouts(TapTargetView.java:709)
                                                                       at com.getkeepsafe.taptargetview.TapTargetView$9.run(TapTargetView.java:398)
                                                                       at com.getkeepsafe.taptargetview.ViewUtil$1.onGlobalLayout(ViewUtil.java:60)
                                                                       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:646)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1724)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                       at dalvik.system.NativeStart.main(Native Method)

:**

**4.1.4:**

**Comment by xiphirx** [comment]
Please update to the latest version. This has already been fixed
